version: '3.5'
services:

  spark-master:
    image: ${REGISTRY}/${USERNAME}/${IMAGENAME}:${IMAGETAG}
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    user: root
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
    networks:
     - datalabframework

  spark-worker-1:
    image: ${REGISTRY}/${USERNAME}/${IMAGENAME}:${IMAGETAG}
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    user: root
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    volumes:
      - ./conf/worker:/conf
    ports:
      - 8081:8081
    networks:
     - datalabframework

  spark-worker-2:
    image: ${REGISTRY}/${USERNAME}/${IMAGENAME}:${IMAGETAG}
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-2
    user: root
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    volumes:
      - ./conf/worker:/conf
    ports:
      - 8082:8081
    networks:
     - datalabframework

networks:
  datalabframework:
    name: datalabframework
    driver: bridge
    external: true
